// by Persian MO

//player addEventHandler ["Fired",{ if (_this select 1 != "THROW" && _this select 1 != "PUT") then {_this execVM "scripts\fs.sqf"};}];
_unit = _this select 0;

_random = 60;
_rs = floor(random _random);
if (_rs == 30) then {

	
_sound = selectRandom [

"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\015_Targeting\Attack_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\015_Targeting\Attack_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\015_Targeting\Engage_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\015_Targeting\Engage_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\015_Targeting\Fire_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\015_Targeting\Fire_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\020_Names\Amin.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\020_Names\Fahim.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\020_Names\Habibi.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\020_Names\Jawadi.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\020_Names\Masood.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\020_Names\Nazari.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\020_Names\Yousuf.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveBack_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveLeft_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveRight_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveUp_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\Advance.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\CombatOpenFire_3.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\CombatOpenFire_4.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\Danger.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\FlankLeft.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\FlankRight.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\FormColumn.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\FormDiamond.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\FormLine.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\FormOnMe.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\FormVee.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\GetReadyToFight.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\GoProne_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\KeepFocused.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\LockAndLoad.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\OnYourFeet.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\PrepareForContact.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\RallyUp.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\Regroup.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\ReturnToFormation.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\StayAlert.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\StayBack.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\StayLow.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\Stop.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\SuppressiveFire.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\TakeCover.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\100_Commands\WeaponsFree.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\110_Com_Announce\HeIsDown.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\110_Com_Announce\HostileDown.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\110_Com_Announce\Ready.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\110_Com_Announce\ScratchOne.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\110_Com_Announce\StandingBy.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\110_Com_Announce\Waiting.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\130_Com_Reply\Attacking.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\130_Com_Reply\confirmation1_3.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\130_Com_Reply\confirmation1_10.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\130_Com_Reply\confirmation2_6.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\130_Com_Reply\EngagingTarget.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\130_Com_Reply\OnTheMove.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\130_Com_Reply\OnTheWay_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\130_Com_Reply\Supporting.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\130_Com_Reply\Suppressing_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CheeringE_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CheeringE_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CheeringE_5.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_3.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_4.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\ContactE_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\ContactE_3.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_4.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_5.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_7.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_6.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CoverMeE_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\CoverMeE_3.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\EndangeredE_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\EndangeredE_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\EndangeredE_3.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\IncomingGrenadeE_2.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\IncomingGrenadeE_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\ReloadingE_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\ReloadingE_4.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\ReloadingE_5.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\UnderFireE_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\UnderFireE_3.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\WitnessKilledE_1.ogg",
"a3\dubbing_radio_f\data\per\Male01PER\RadioProtocolPER\Combat\200_CombatShouts\WitnessKilledE_3.ogg",

"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\015_Targeting\Attack_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\015_Targeting\Attack_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\015_Targeting\Engage_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\015_Targeting\Engage_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\015_Targeting\Fire_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\015_Targeting\Fire_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\020_Names\Amin.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\020_Names\Fahim.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\020_Names\Habibi.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\020_Names\Jawadi.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\020_Names\Masood.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\020_Names\Nazari.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\020_Names\Yousuf.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveBack_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveLeft_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveRight_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveUp_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\Advance.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\CombatOpenFire_3.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\CombatOpenFire_4.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\Danger.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\FlankLeft.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\FlankRight.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\FormColumn.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\FormDiamond.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\FormLine.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\FormOnMe.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\FormVee.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\GetReadyToFight.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\GoProne_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\KeepFocused.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\LockAndLoad.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\OnYourFeet.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\PrepareForContact.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\RallyUp.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\Regroup.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\ReturnToFormation.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\StayAlert.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\StayBack.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\StayLow.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\Stop.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\SuppressiveFire.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\TakeCover.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\100_Commands\WeaponsFree.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\110_Com_Announce\HeIsDown.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\110_Com_Announce\HostileDown.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\110_Com_Announce\Ready.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\110_Com_Announce\ScratchOne.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\110_Com_Announce\StandingBy.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\110_Com_Announce\Waiting.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\130_Com_Reply\Attacking.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\130_Com_Reply\confirmation1_3.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\130_Com_Reply\confirmation1_10.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\130_Com_Reply\confirmation2_6.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\130_Com_Reply\EngagingTarget.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\130_Com_Reply\OnTheMove.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\130_Com_Reply\OnTheWay_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\130_Com_Reply\Supporting.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\130_Com_Reply\Suppressing_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CheeringE_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CheeringE_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CheeringE_5.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_3.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_4.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\ContactE_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\ContactE_3.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_4.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_5.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_7.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_6.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CoverMeE_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\CoverMeE_3.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\EndangeredE_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\EndangeredE_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\EndangeredE_3.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\IncomingGrenadeE_2.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\IncomingGrenadeE_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\ReloadingE_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\ReloadingE_4.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\ReloadingE_5.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\UnderFireE_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\UnderFireE_3.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\WitnessKilledE_1.ogg",
"a3\dubbing_radio_f\data\per\Male03PER\RadioProtocolPER\Combat\200_CombatShouts\WitnessKilledE_3.ogg",

"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\015_Targeting\Attack_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\015_Targeting\Attack_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\015_Targeting\Engage_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\015_Targeting\Engage_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\015_Targeting\Fire_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\015_Targeting\Fire_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\020_Names\Amin.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\020_Names\Fahim.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\020_Names\Habibi.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\020_Names\Jawadi.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\020_Names\Masood.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\020_Names\Nazari.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\020_Names\Yousuf.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveBack_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveLeft_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveRight_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\070_MoveDirectionRelative1\moveUp_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\Advance.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\CombatOpenFire_3.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\CombatOpenFire_4.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\Danger.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\FlankLeft.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\FlankRight.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\FormColumn.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\FormDiamond.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\FormLine.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\FormOnMe.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\FormVee.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\GetReadyToFight.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\GoProne_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\KeepFocused.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\LockAndLoad.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\OnYourFeet.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\PrepareForContact.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\RallyUp.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\Regroup.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\ReturnToFormation.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\StayAlert.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\StayBack.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\StayLow.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\Stop.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\SuppressiveFire.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\TakeCover.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\100_Commands\WeaponsFree.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\110_Com_Announce\HeIsDown.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\110_Com_Announce\HostileDown.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\110_Com_Announce\Ready.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\110_Com_Announce\ScratchOne.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\110_Com_Announce\StandingBy.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\110_Com_Announce\Waiting.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\130_Com_Reply\Attacking.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\130_Com_Reply\confirmation1_3.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\130_Com_Reply\confirmation1_10.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\130_Com_Reply\confirmation2_6.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\130_Com_Reply\EngagingTarget.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\130_Com_Reply\OnTheMove.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\130_Com_Reply\OnTheWay_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\130_Com_Reply\Supporting.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\130_Com_Reply\Suppressing_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CheeringE_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CheeringE_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CheeringE_5.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_3.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CombatGenericE_4.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\ContactE_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\ContactE_3.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_4.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_5.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_7.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CoveringE_6.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CoverMeE_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\CoverMeE_3.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\EndangeredE_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\EndangeredE_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\EndangeredE_3.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\IncomingGrenadeE_2.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\IncomingGrenadeE_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\ReloadingE_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\ReloadingE_4.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\ReloadingE_5.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\UnderFireE_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\UnderFireE_3.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\WitnessKilledE_1.ogg",
"a3\dubbing_radio_f\data\per\Male02PER\RadioProtocolPER\Combat\200_CombatShouts\WitnessKilledE_3.ogg"







];




playSound3D [_sound, _unit, false, getPosASL _unit, 3, 1, 0];



};

