// ACE Advanced Ballistics
force force ace_advanced_ballistics_ammoTemperatureEnabled = true;
force force ace_advanced_ballistics_barrelLengthInfluenceEnabled = true;
force force ace_advanced_ballistics_bulletTraceEnabled = true;
force force ace_advanced_ballistics_enabled = false;
force force ace_advanced_ballistics_muzzleVelocityVariationEnabled = true;
force force ace_advanced_ballistics_simulationInterval = 0.05;

// ACE Advanced Fatigue
force force ace_advanced_fatigue_enabled = true;
force force ace_advanced_fatigue_enableStaminaBar = true;
ace_advanced_fatigue_fadeStaminaBar = true;
force force ace_advanced_fatigue_loadFactor = 0.7;
force force ace_advanced_fatigue_performanceFactor = 1.1;
force force ace_advanced_fatigue_recoveryFactor = 2.5;
force force ace_advanced_fatigue_swayFactor = 0.9;
force force ace_advanced_fatigue_terrainGradientFactor = 0.3;



// ACE Advanced Throwing
force force ace_advanced_throwing_enabled = true;
force force ace_advanced_throwing_enablePickUp = true;
force force ace_advanced_throwing_enablePickUpAttached = true;
force force ace_advanced_throwing_showMouseControls = true;
force force ace_advanced_throwing_showThrowArc = true;

// ACE Advanced Vehicle Damage
force force ace_vehicle_damage_enableCarDamage = false;
force force ace_vehicle_damage_enabled = false;
force force ace_vehicle_damage_removeAmmoDuringCookoff = false;

// ACE Armor Adjuster
force force  AAA_VAR_AI_ARMOR_COEF = 1;
force force AAA_VAR_BLUFOR_ARMOR_COEF = 0;
force force AAA_VAR_CIV_ARMOR_COEF = 0;
force force AAA_VAR_EXPLOSIVE_MULT = 0.5;
force force AAA_VAR_HITABDOMEN_ENABLED = true;
force force AAA_VAR_HITABDOMEN_MULT = 5;
force force AAA_VAR_HITARMS_ENABLED = true;
force force AAA_VAR_HITARMS_MULT = 3;
force force AAA_VAR_HITBODY_ENABLED = true;
force force AAA_VAR_HITBODY_MULT = 5;
force force AAA_VAR_HITCHEST_ENABLED = true;
force force AAA_VAR_HITCHEST_MULT = 5;
force force AAA_VAR_HITDIAPHRAGM_ENABLED = true;
force force AAA_VAR_HITDIAPHRAGM_MULT = 5;
force force AAA_VAR_HITFACE_ENABLED = true;
force force AAA_VAR_HITFACE_MULT = 3;
force force AAA_VAR_HITHANDS_ENABLED = true;
force force AAA_VAR_HITHANDS_MULT = 3;
force force AAA_VAR_HITHEAD_ENABLED = true;
force force AAA_VAR_HITHEAD_MULT = 3;
force force AAA_VAR_HITLEGS_ENABLED = true;
force force AAA_VAR_HITLEGS_MULT = 3;
force force AAA_VAR_HITNECK_ENABLED = true;
force force AAA_VAR_HITNECK_MULT = 3;
force force AAA_VAR_HITPELVIS_ENABLED = true;
force force AAA_VAR_HITPELVIS_MULT = 5;
force force AAA_VAR_IND_ARMOR_COEF = 0;
force force AAA_VAR_MOD_ENABLED = true;
force force AAA_VAR_OPFOR_ARMOR_COEF = 0;
force force AAA_VAR_PLAYER_ARMOR_COEF = 1;

// ACE Arsenal
force force ace_arsenal_allowDefaultLoadouts = true;
force force ace_arsenal_allowSharedLoadouts = true;
ace_arsenal_camInverted = false;
force force ace_arsenal_enableIdentityTabs = true;
ace_arsenal_enableModIcons = true;
ace_arsenal_EnableRPTLog = false;
ace_arsenal_fontHeight = 4.5;
ace_arsenal_loadoutsSaveFace = true;
ace_arsenal_loadoutsSaveInsignia = true;
ace_arsenal_loadoutsSaveVoice = true;

// ACE Artillery
force ace_artillerytables_advancedCorrections = false;
force ace_artillerytables_disableArtilleryComputer = true;
force ace_mk6mortar_airResistanceEnabled = false;
force ace_mk6mortar_allowCompass = true;
force ace_mk6mortar_allowComputerRangefinder = true;
force ace_mk6mortar_useAmmoHandling = false;

// ACE Captives
force ace_captives_allowHandcuffOwnSide = true;
force ace_captives_allowSurrender = true;
force ace_captives_requireSurrender = 1;
force ace_captives_requireSurrenderAi = true;

// ACE Casings
force ace_casings_enabled = false;
force ace_casings_maxCasings = 250;

// ACE Common
force force ace_common_allowFadeMusic = true;
force force ace_common_checkPBOsAction = 0;
force force ace_common_checkPBOsCheckAll = false;
force force ace_common_checkPBOsWhitelist = "[]";
ace_common_displayTextColor = [0,0,0,0.1];
ace_common_displayTextFontColor = [1,1,1,1];
ace_common_epilepsyFriendlyMode = false;
ace_common_progressBarInfo = 2;
ace_common_settingFeedbackIcons = 1;
ace_common_settingProgressBarLocation = 0;

// ACE Cook off
force force ace_cookoff_ammoCookoffDuration = 0.5;
force force ace_cookoff_destroyVehicleAfterCookoff = false;
force force ace_cookoff_enable = 2;
force force ace_cookoff_enableAmmobox = false;
force force ace_cookoff_enableAmmoCookoff = true;
force force ace_cookoff_enableFire = true;
force force ace_cookoff_probabilityCoef = 0.5;

// ACE Crew Served Weapons
force force ace_csw_ammoHandling = 1;
force force ace_csw_defaultAssemblyMode = false;
ace_csw_dragAfterDeploy = false;
force force ace_csw_handleExtraMagazines = true;
force ace_csw_handleExtraMagazinesType = 1;
force force ace_csw_progressBarTimeCoefficent = 1;

// ACE Dragging
force ace_dragging_dragAndFire = true;

// ACE Explosives
force ace_explosives_customTimerDefault = 30;
force ace_explosives_customTimerMax = 5400;
force ace_explosives_customTimerMin = 15;
force force ace_explosives_explodeOnDefuse = false;
force force ace_explosives_punishNonSpecialists = false;
force force ace_explosives_requireSpecialist = false;

// Ace Extension (Gestures)
kka3_gesture1 = "kka3_arrested";
kka3_gesture2 = "kka3_arrested";
kka3_gesture3 = "kka3_arrested";
kka3_gesture4 = "kka3_arrested";
kka3_gesture5 = "kka3_arrested";
kka3_gesture6 = "kka3_arrested";
kka3_gesture7 = "kka3_arrested";
kka3_gesture8 = "kka3_arrested";
kka3_gesture9 = "kka3_arrested";
kka3_hotkeydisabled = false;
kka3_placeholder = false;

// ACE Field Rations
force acex_field_rations_affectAdvancedFatigue = true;
force acex_field_rations_enabled = false;
force acex_field_rations_hudShowLevel = 0;
force acex_field_rations_hudTransparency = -1;
force acex_field_rations_hudType = 0;
force acex_field_rations_hungerSatiated = 1;
force acex_field_rations_terrainObjectActions = true;
force acex_field_rations_thirstQuenched = 1;
force acex_field_rations_timeWithoutFood = 2;
force acex_field_rations_timeWithoutWater = 2;
force acex_field_rations_waterSourceActions = 2;

// ACE Fire
force force ace_fire_dropWeapon = 0;
force force ace_fire_enabled = false;
force force ace_fire_enableFlare = false;
force force ace_fire_enableScreams = false;

// ACE Fortify
force force ace_fortify_markObjectsOnMap = 1;
force force ace_fortify_timeCostCoefficient = 0;
force force ace_fortify_timeMin = 0;
force force acex_fortify_settingHint = 0;

// ACE Fragmentation Simulation
force force ace_frag_enabled = true;
force force ace_frag_maxTrack = 25;
force force ace_frag_maxTrackPerFrame = 25;
force force ace_frag_reflectionsEnabled = false;
force force ace_frag_spallEnabled = true;

// ACE G-Forces
force ace_gforces_coef = 0.5;
force force ace_gforces_enabledFor = 1;

// ACE Goggles
ace_goggles_effects = 0;
ace_goggles_showClearGlasses = false;
ace_goggles_showInThirdPerson = false;

// ACE Grenades
force ace_grenades_convertExplosives = true;

// ACE Grenades in hatches - Tweaked
force grenades_hatches_main_allowedBehaviorSetting = "['CARELESS','SAFE','AWARE','COMBAT','STEALTH']";
force grenades_hatches_main_allowedGrenadesSetting = "['HandGrenade','MiniGrenade']";
force grenades_hatches_main_blacklistVehiclesInheritanceSetting = "[]";
force grenades_hatches_main_blacklistVehiclesSetting = "[]";
force grenades_hatches_main_damageDealtCrew = 5;
force grenades_hatches_main_damageDealtCrewVanilla = 0.25;
force grenades_hatches_main_damageDealtEngine = 0.5;
force grenades_hatches_main_damageDealtEngineMax = 0.5;
force grenades_hatches_main_damageDealtHull = 0.75;
force grenades_hatches_main_damageDealtHullMax = 0.75;
force grenades_hatches_main_damageDealtTurret = 0.5;
force grenades_hatches_main_damageDealtTurretMax = 0.5;
force grenades_hatches_main_damageType = true;
force grenades_hatches_main_delayExplosion = 5;
force grenades_hatches_main_delayInteraction = 3;
force grenades_hatches_main_disablePlayerAmbush = false;
force grenades_hatches_main_distanceInteraction = 10;
force grenades_hatches_main_enableKnowledgeMultiplier = false;
force grenades_hatches_main_forceCrewDismount = false;
force grenades_hatches_main_knowledgeMultiplier = 5;
force grenades_hatches_main_whitelistVehiclesInheritanceSetting = "['Tank','Wheeled_Apc_F']";
force grenades_hatches_main_whitelistVehiclesSetting = "[]";

// ACE Headless
force acex_headless_delay = 15;
force acex_headless_enabled = true;
force acex_headless_endMission = 0;
force acex_headless_log = true;
force acex_headless_transferLoadout = 1;

// ACE Hearing
force force ace_hearing_autoAddEarplugsToUnits = true;
force force ace_hearing_disableEarRinging = true;
force force ace_hearing_earplugsVolume = 0.5;
force force ace_hearing_enableCombatDeafness = false;
force force ace_hearing_enabledForZeusUnits = false;
force force ace_hearing_unconsciousnessVolume = 0.4;

// ACE Interaction
force force ace_interaction_disableNegativeRating = true;
force force ace_interaction_enableGroupRenaming = false;
force force ace_interaction_enableMagazinePassing = true;
force force ace_interaction_enableTeamManagement = true;
ace_interaction_enableWeaponAttachments = true;
force ace_interaction_interactWithTerrainObjects = false;

// ACE Interaction Menu
ace_gestures_showOnInteractionMenu = 2;
ace_interact_menu_actionOnKeyRelease = true;
ace_interact_menu_addBuildingActions = false;
ace_interact_menu_alwaysUseCursorInteraction = true;
ace_interact_menu_alwaysUseCursorSelfInteraction = true;
ace_interact_menu_colorShadowMax = [0,0,0,1];
ace_interact_menu_colorShadowMin = [0,0,0,0.25];
ace_interact_menu_colorTextMax = [1,1,1,1];
ace_interact_menu_colorTextMin = [1,1,1,0.25];
ace_interact_menu_consolidateSingleChild = false;
ace_interact_menu_cursorKeepCentered = false;
ace_interact_menu_cursorKeepCenteredSelfInteraction = false;
ace_interact_menu_menuAnimationSpeed = 0;
ace_interact_menu_menuBackground = 0;
ace_interact_menu_menuBackgroundSelf = 0;
ace_interact_menu_selectorColor = [1,0,0];
ace_interact_menu_shadowSetting = 2;
ace_interact_menu_textSize = 2;
ace_interact_menu_useListMenu = true;
ace_interact_menu_useListMenuSelf = true;

// ACE Interaction Menu (Self) - More
ace_interact_menu_more__ACE_Animations = false;
ace_interact_menu_more__ACE_CheckAirTemperature = false;
ace_interact_menu_more__ace_csw_deploy = false;
ace_interact_menu_more__ACE_Equipment = false;
ace_interact_menu_more__ACE_Explosives = false;
ace_interact_menu_more__ace_field_rations = false;
ace_interact_menu_more__ace_fortify = false;
ace_interact_menu_more__ace_gestures = false;
ace_interact_menu_more__ace_intelitems = false;
ace_interact_menu_more__ACE_MapFlashlight = false;
ace_interact_menu_more__ACE_MapGpsHide = false;
ace_interact_menu_more__ACE_MapGpsShow = false;
ace_interact_menu_more__ACE_MapTools = false;
ace_interact_menu_more__ACE_Medical = false;
ace_interact_menu_more__ACE_MoveRallypoint = false;
ace_interact_menu_more__ACE_RepackMagazines = false;
ace_interact_menu_more__ace_sandbag_place = false;
ace_interact_menu_more__ACE_StartSurrenderingSelf = false;
ace_interact_menu_more__ACE_StopEscortingSelf = false;
ace_interact_menu_more__ACE_StopSurrenderingSelf = false;
ace_interact_menu_more__ACE_Tags = false;
ace_interact_menu_more__ACE_TeamManagement = false;
ace_interact_menu_more__ace_zeus_create = false;
ace_interact_menu_more__ace_zeus_delete = false;
ace_interact_menu_more__aceax_ingame_gear = false;
ace_interact_menu_more__acex_sitting_Stand = false;
ace_interact_menu_more__grad_captiveWalking_functions_freeInVehicle = false;
ace_interact_menu_more__Medical = false;
ace_interact_menu_more__TFAR_Radio = false;

// ACE Interaction Menu (Self) - Move to Root
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Advance = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_CeaseFire = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Cover = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Engage = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Follow = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Forward = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Freeze = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Go = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Hold = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Point = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Regroup = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Stop = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Up = false;
ace_interact_menu_moveToRoot__ACE_Animations__ace_gestures_cat_gestures__ace_gestures_Warning = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_actions = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_actions__Inspect Weapon = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_actions__Kata = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_actions__Panic = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_actions__Pissing = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_actions__Play Dead = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_actions__Pushups = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_actions__Suicide = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_actions__Tighten Shoelace = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_cancel = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Contact 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Contact 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Drunk = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Dubstep = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Dubstep Pop = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Duo (Ivan) = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Duo (Stefan) = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__HipHop = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Metal = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Nightclub = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Robo = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Russian = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__Stefan = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_dance__ZOZO = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Angery = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Confused = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Crazy = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Sad = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Satisfied = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Shouting = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Sleeping = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Sleepy = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Smile = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Smirking = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Suffering = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Talking = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__TFI_ace_emote1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__TFI_ace_emote1__Dead 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__TFI_ace_emote1__Dead 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__TFI_ace_emote2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__TFI_ace_emote2__Nod No = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__TFI_ace_emote2__Nod Yes = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__TFI_ace_emote3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__TFI_ace_emote3__Winking L = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__TFI_ace_emote3__Winking R = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Unconscious = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_emote__Yawning = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture11 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture11__Aggressive 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture11__Aggressive 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture12 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture12__Agreeing 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture12__Agreeing 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture13 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture13__Approximate 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture13__Approximate 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture13__Approximate 3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture14 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture14__Defensive 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture14__Defensive 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture15 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture15__Disagreeing 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture15__Disagreeing 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture15__Disagreeing 3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture16 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture16__Dismissing 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture1__TFI_ace_gesture16__Dismissing 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Bird = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Clapping = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Finger Pistol = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__High Five = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Horns = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Jackoff = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Kiss = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Mahalo = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Ok = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Paper = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Rock = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Scissors = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Scratch = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture21 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture21__Facepalm 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture21__Facepalm 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture21__Facepalm 3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture21__Facepalm 4 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture21__Facepalm 5 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture22 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture22__Dab 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture22__Dab 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture22__Dab 3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture23 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture23__Peace 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture23__Peace 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture24 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture24__Wave 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture24__Wave 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture24__Wave 3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture24__Wave 4 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture24__Wave 5 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture24__Wave 6 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture25 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture25__Point Back = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture25__Point Down = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture25__Point Front = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture25__Point Left = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture25__Point Right = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture25__Point Up = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture26 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture26__Selfie 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture26__Selfie 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture27 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture27__Surrender 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture27__Surrender 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture28 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture28__Yawn 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture28__Yawn 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture29 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture29__Sneeze 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__TFI_ace_gesture29__Sneeze 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture2__Think = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture3__Drake No = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture3__Drake Yes = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture3__Facepalm = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture3__I Want You = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_gesture__TFI_ace_gesture3__Warming Hands = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose1__Attention 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose1__Attention 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose1__Attention 3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose1__Attention 4 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose1__Attention 5 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose1__Attention 6 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Crouch = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Crouch Thumbup = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Emergency Stop = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Engines Off = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Engines On = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Launch = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Left = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Right = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Slow = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Stop = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose2__Straight = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 10 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 11 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 12 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 13 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 14 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 15 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 16 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 17 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 18 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 19 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 20 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 4 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 5 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 6 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 7 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 8 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose3__Idle 9 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 1 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 10 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 11 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 12 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 13 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 14 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 15 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 16 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 17 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 18 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 19 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 2 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 20 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 21 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 22 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 23 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 24 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 25 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 3 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 4 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 5 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 6 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 7 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 8 = false;
ace_interact_menu_moveToRoot__ACE_Animations__TFI_ace_pose__TFI_ace_pose4__Static 9 = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_atragmx_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_attach_Attach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_attach_Detach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_CheckDogtags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_Chemlights = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_dagr_menu = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_dagr_menu__ace_dagr_toggle = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_goggles_wipeGlasses = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_status = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponOff = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponSwap = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponTo = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_huntir_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_interaction_weaponAttachments = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open__ace_kestrel4500_hide = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open__ace_kestrel4500_show = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_marker_flags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure__ace_microdagr_close = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure__ace_microdagr_show = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_activate = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_connectHeadphones = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_deactivate = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_disconnectHeadphones = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_mk6mortar_rangetable = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CheckTemperature = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CheckTemperatureSpareBarrels = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CoolWeaponWithItem = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_SwapBarrel = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_UnJam = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_PutInEarplugs = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open__ace_rangecard_makeCopy = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open__ace_rangecard_openCopy = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_reload_checkAmmo = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_RemoveEarplugs = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_scopes_adjustZero = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_scopes_resetZero = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_spottingscope_place = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_TacticalLadders = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__ace_trenches_digEnvelopeBig = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__ace_trenches_digEnvelopeSmall = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeGiant = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeLongNameEmplacment = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeShort = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeVehicle = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_tripod_place = false;
ace_interact_menu_moveToRoot__ACE_Equipment__addSound = false;
ace_interact_menu_moveToRoot__ACE_Equipment__AMP_DeployDoorWedge = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_onBack = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_onChest = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_swap = false;
ace_interact_menu_moveToRoot__ACE_Equipment__GCutter = false;
ace_interact_menu_moveToRoot__ACE_Equipment__openCrossPanel = false;
ace_interact_menu_moveToRoot__ACE_Equipment__placeAED = false;
ace_interact_menu_moveToRoot__ACE_Equipment__removeSound = false;
ace_interact_menu_moveToRoot__ACE_Equipment__UK3CB_Assemble_Javelin = false;
ace_interact_menu_moveToRoot__ACE_Equipment__UK3CB_Attach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__UK3CB_Attach_Helmet = false;
ace_interact_menu_moveToRoot__ACE_Equipment__UK3CB_Detach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__UK3CB_Detach_Helmet = false;
ace_interact_menu_moveToRoot__ACE_Equipment__UK3CB_Disassemble_Javelin = false;
ace_interact_menu_moveToRoot__ACE_Equipment__UK3CB_DropBackpack = false;
ace_interact_menu_moveToRoot__ACE_Equipment__UK3CB_PickupBackpack = false;
ace_interact_menu_moveToRoot__ACE_Explosives__ACE_Cellphone = false;
ace_interact_menu_moveToRoot__ACE_Explosives__ACE_Place = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Advance = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_CeaseFire = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Cover = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Engage = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Follow = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Forward = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Freeze = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Go = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Hold = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Point = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Regroup = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Stop = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Up = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Warning = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlignCompass = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlignNorth = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsHide = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsShowNormal = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsShowSmall = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_ArmLeft = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_ArmRight = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Head = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_LegLeft = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_LegRight = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Menu = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Torso = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Torso__TriageCard = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_BecomeLeader = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamBlue = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamGreen = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamRed = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamYellow = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_LeaveGroup = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_LeaveTeam = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_RenameGroup = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__diwako_dui_buddy_buddy_action_team_remove = false;
ace_interact_menu_moveToRoot__Medical__ACE_Head = false;
ace_interact_menu_moveToRoot__Medical__ACE_Head__CheckBloodPressure = false;

// ACE Logistics
ace_cargo_carryAfterUnload = true;
force force ace_cargo_enable = true;
ace_cargo_enableRename = true;
force force ace_cargo_loadTimeCoefficient = 5;
ace_cargo_openAfterUnload = 0;
force force ace_cargo_paradropTimeCoefficent = 2.5;
force force ace_rearm_distance = 20;
force force ace_rearm_level = 0;
force force ace_rearm_supply = 0;
force force ace_refuel_hoseLength = 12;
force ace_refuel_progressDuration = 2;
force force ace_refuel_rate = 1;
force force ace_repair_addSpareParts = true;
force force ace_repair_autoShutOffEngineWhenStartingRepair = true;
force force ace_repair_consumeItem_toolKit = 0;
ace_repair_displayTextOnRepair = true;
force force ace_repair_engineerSetting_fullRepair = 1;
force force ace_repair_engineerSetting_repair = 1;
force force ace_repair_engineerSetting_wheel = 0;
force force ace_repair_fullRepairLocation = 2;
force force ace_repair_fullRepairRequiredItems = [];
force force ace_repair_locationsBoostTraining = true;
force force ace_repair_miscRepairRequiredItems = [];
force force ace_repair_repairDamageThreshold = 0.2;
force force ace_repair_repairDamageThreshold_engineer = 0.5;
force force ace_repair_wheelRepairRequiredItems = [];
force ace_towing_addRopeToVehicleInventory = true;

// ACE Magazine Repack
ace_magazinerepack_repackAnimation = true;
ace_magazinerepack_repackLoadedMagazines = true;
force force ace_magazinerepack_timePerAmmo = 1;
force force ace_magazinerepack_timePerBeltLink = 4;
force force ace_magazinerepack_timePerMagazine = 1;

// ACE Map
force force ace_map_BFT_Enabled = false;
force force ace_map_BFT_HideAiGroups = true;
force force ace_map_BFT_Interval = 2;
force force ace_map_BFT_ShowPlayerNames = false;
force force ace_map_DefaultChannel = 1;
force force ace_map_mapGlow = true;
force force ace_map_mapIllumination = true;
force force ace_map_mapLimitZoom = false;
force force ace_map_mapShake = true;
force force ace_map_mapShowCursorCoordinates = false;
force force ace_markers_moveRestriction = 2;
ace_markers_timestampEnabled = true;
ace_markers_timestampFormat = "HH:MM";
ace_markers_timestampHourFormat = 24;

// ACE Map Gestures
ace_map_gestures_allowCurator = true;
ace_map_gestures_allowSpectator = true;
force force ace_map_gestures_briefingMode = 4;
ace_map_gestures_defaultColor = [0.744662,0.567105,0,0.7];
ace_map_gestures_defaultLeadColor = [1,0.88,0,0.95];
force force ace_map_gestures_enabled = true;
force force ace_map_gestures_interval = 0.03;
force force ace_map_gestures_maxRange = 10;
force force ace_map_gestures_maxRangeCamera = 14;
ace_map_gestures_nameTextColor = [0.2,0.2,0.2,0.3];
force force ace_map_gestures_onlyShowFriendlys = true;

// ACE Map Tools
force force ace_maptools_drawStraightLines = true;
ace_maptools_rotateModifierKey = 1;

// ACE Medical
force force ace_medical_ai_enabledFor = 2;
force force ace_medical_AIDamageThreshold = 2;
force force ace_medical_bleedingCoefficient = 1.3;
force force ace_medical_blood_bloodLifetime = 60;
force force ace_medical_blood_enabledFor = 0;
force force ace_medical_blood_maxBloodObjects = 50;
force force ace_medical_deathChance = 0.5;
force force ace_medical_enableVehicleCrashes = true;
force force ace_medical_fatalDamageSource = 2;
force force ace_medical_feedback_bloodVolumeEffectType = 2;
force force ace_medical_feedback_enableHUDIndicators = true;
force force ace_medical_feedback_painEffectType = 2;
force force ace_medical_fractureChance = 0.5;
force force ace_medical_fractures = 1;
force force ace_medical_gui_bloodLossColor_0 = [1,1,1,1];
force force ace_medical_gui_bloodLossColor_1 = [1,0.95,0.64,1];
force force ace_medical_gui_bloodLossColor_2 = [1,0.87,0.46,1];
force force ace_medical_gui_bloodLossColor_3 = [1,0.8,0.33,1];
force force ace_medical_gui_bloodLossColor_4 = [1,0.72,0.24,1];
force force ace_medical_gui_bloodLossColor_5 = [1,0.63,0.15,1];
force force ace_medical_gui_bloodLossColor_6 = [1,0.54,0.08,1];
force force ace_medical_gui_bloodLossColor_7 = [1,0.43,0.02,1];
force force ace_medical_gui_bloodLossColor_8 = [1,0.3,0,1];
force force ace_medical_gui_bloodLossColor_9 = [1,0,0,1];
force force ace_medical_gui_damageColor_0 = [1,1,1,1];
force force ace_medical_gui_damageColor_1 = [0.75,0.95,1,1];
force force ace_medical_gui_damageColor_2 = [0.62,0.86,1,1];
force force ace_medical_gui_damageColor_3 = [0.54,0.77,1,1];
force force ace_medical_gui_damageColor_4 = [0.48,0.67,1,1];
force force ace_medical_gui_damageColor_5 = [0.42,0.57,1,1];
force force ace_medical_gui_damageColor_6 = [0.37,0.47,1,1];
force force ace_medical_gui_damageColor_7 = [0.31,0.36,1,1];
force force ace_medical_gui_damageColor_8 = [0.22,0.23,1,1];
force force ace_medical_gui_damageColor_9 = [0,0,1,1];
force force ace_medical_gui_enableActions = 0;
force force ace_medical_gui_enableMedicalMenu = 1;
force force ace_medical_gui_enableSelfActions = true;
force force ace_medical_gui_interactionMenuShowTriage = 1;
force force ace_medical_gui_maxDistance = 5;
force force ace_medical_gui_openAfterTreatment = true;
force force ace_medical_gui_showBloodlossEntry = true;
force force ace_medical_ivFlowRate = 10;
force force ace_medical_limping = 1;
force force ace_medical_painCoefficient = 1;
force force ace_medical_painUnconsciousChance = 0.5;
force force ace_medical_playerDamageThreshold = 2;
force force ace_medical_spontaneousWakeUpChance = 0.75;
force force ace_medical_spontaneousWakeUpEpinephrineBoost = 10;
force force ace_medical_statemachine_AIUnconsciousness = true;
force force ace_medical_statemachine_cardiacArrestBleedoutEnabled = false;
force force ace_medical_statemachine_cardiacArrestTime = 420;
force force ace_medical_statemachine_fatalInjuriesAI = 0;
force force ace_medical_statemachine_fatalInjuriesPlayer = 0;
force force ace_medical_treatment_advancedBandages = 2;
force force ace_medical_treatment_advancedDiagnose = 2;
force force ace_medical_treatment_advancedMedication = true;
force force ace_medical_treatment_allowBodyBagUnconscious = false;
force force ace_medical_treatment_allowLitterCreation = true;
force force ace_medical_treatment_allowSelfIV = 1;
force force ace_medical_treatment_allowSelfPAK = 0;
force force ace_medical_treatment_allowSelfStitch = 0;
force force ace_medical_treatment_allowSharedEquipment = 1;
force force ace_medical_treatment_clearTrauma = 1;
force force ace_medical_treatment_consumePAK = 0;
force force ace_medical_treatment_consumeSurgicalKit = 0;
force force ace_medical_treatment_convertItems = 0;
force force ace_medical_treatment_cprSuccessChanceMax = 0.6;
force force ace_medical_treatment_cprSuccessChanceMin = 0.4;
force force ace_medical_treatment_holsterRequired = 0;
force force ace_medical_treatment_litterCleanupDelay = 60;
force force ace_medical_treatment_locationEpinephrine = 0;
force force ace_medical_treatment_locationIV = 0;
force force ace_medical_treatment_locationPAK = 3;
force force ace_medical_treatment_locationsBoostTraining = true;
force force ace_medical_treatment_locationSurgicalKit = 0;
force force ace_medical_treatment_maxLitterObjects = 500;
force force ace_medical_treatment_medicEpinephrine = 0;
force force ace_medical_treatment_medicIV = 0;
force force ace_medical_treatment_medicPAK = 1;
force force ace_medical_treatment_medicSurgicalKit = 1;
force force ace_medical_treatment_timeCoefficientPAK = 1;
force force ace_medical_treatment_treatmentTimeAutoinjector = 5;
force force ace_medical_treatment_treatmentTimeBodyBag = 10;
force force ace_medical_treatment_treatmentTimeCPR = 10;
force force ace_medical_treatment_treatmentTimeIV = 12;
force force ace_medical_treatment_treatmentTimeSplint = 7;
force force ace_medical_treatment_treatmentTimeTourniquet = 2;
force force ace_medical_treatment_woundReopenChance = 0.3;
force force ace_medical_treatment_woundStitchTime = 3;

// ACE Name Tags
ace_nametags_defaultNametagColor = [0.77,0.51,0.08,1];
ace_nametags_nametagColorBlue = [0.67,0.67,1,1];
ace_nametags_nametagColorGreen = [0.67,1,0.67,1];
ace_nametags_nametagColorMain = [1,1,1,1];
ace_nametags_nametagColorRed = [1,0.67,0.67,1];
ace_nametags_nametagColorYellow = [1,1,0.67,1];
force ace_nametags_playerNamesMaxAlpha = 0.8;
force ace_nametags_playerNamesViewDistance = 5;
force ace_nametags_showCursorTagForVehicles = false;
ace_nametags_showNamesForAI = false;
ace_nametags_showPlayerNames = 1;
ace_nametags_showPlayerRanks = true;
ace_nametags_showSoundWaves = 1;
ace_nametags_showVehicleCrewInfo = true;
ace_nametags_tagSize = 2;

// ACE Nightvision
force ace_nightvision_aimDownSightsBlur = 0.1;
force ace_nightvision_disableNVGsWithSights = false;
force ace_nightvision_effectScaling = 0.3;
force ace_nightvision_fogScaling = 0;
force ace_nightvision_noiseScaling = 0.3;
ace_nightvision_shutterEffects = false;

// ACE Overheating
ace_overheating_displayTextOnJam = true;
force ace_overheating_enabled = true;
force ace_overheating_overheatingDispersion = true;
ace_overheating_showParticleEffects = false;
ace_overheating_showParticleEffectsForEveryone = false;
force ace_overheating_unJamFailChance = 0;
force ace_overheating_unJamOnreload = false;

// ACE Pointing
force ace_finger_enabled = true;
ace_finger_indicatorColor = [0.83,0.68,0.21,0.75];
ace_finger_indicatorForSelf = true;
force ace_finger_maxRange = 4;

// ACE Pylons
force force ace_pylons_enabledForZeus = true;
force force ace_pylons_enabledFromAmmoTrucks = true;
force force ace_pylons_rearmNewPylons = false;
force force ace_pylons_requireEngineer = false;
force force ace_pylons_requireToolkit = false;
force force ace_pylons_searchDistance = 15;
force force ace_pylons_timePerPylon = 3;

// ACE Quick Mount
force force ace_quickmount_distance = 3;
force force ace_quickmount_enabled = true;
ace_quickmount_enableMenu = 3;
ace_quickmount_priority = 0;
force force ace_quickmount_speed = 18;

// ACE Respawn
force force ace_respawn_removeDeadBodiesDisconnected = true;
force force ace_respawn_savePreDeathGear = false;

// ACE Scopes
force force ace_scopes_correctZeroing = true;
force force ace_scopes_deduceBarometricPressureFromTerrainAltitude = false;
force force ace_scopes_defaultZeroRange = 100;
force force ace_scopes_enabled = true;
force force ace_scopes_forceUseOfAdjustmentTurrets = true;
force force ace_scopes_overwriteZeroRange = false;
force force ace_scopes_simplifiedZeroing = false;
ace_scopes_useLegacyUI = false;
force force ace_scopes_zeroReferenceBarometricPressure = 1013.25;
force force ace_scopes_zeroReferenceHumidity = 0;
force force ace_scopes_zeroReferenceTemperature = 15;

// ACE Sitting
force acex_sitting_enable = true;

// ACE Spectator
force force ace_spectator_enableAI = true;
ace_spectator_maxFollowDistance = 5;
force force ace_spectator_restrictModes = 0;
force force ace_spectator_restrictVisions = 0;

// ACE Switch Units
force force ace_switchunits_enableSafeZone = true;
force force ace_switchunits_enableSwitchUnits = false;
force force ace_switchunits_safeZoneRadius = 100;
force force ace_switchunits_switchToCivilian = false;
force force ace_switchunits_switchToEast = false;
force force ace_switchunits_switchToIndependent = false;
force force ace_switchunits_switchToWest = false;

// ACE Trenches
force ace_trenches_bigEnvelopeDigDuration = 10;
force ace_trenches_bigEnvelopeRemoveDuration = 5;
force ace_trenches_smallEnvelopeDigDuration = 5;
force ace_trenches_smallEnvelopeRemoveDuration = 5;

// ACE Uncategorized
force force ace_fastroping_requireRopeItems = false;
force ace_gunbag_swapGunbagEnabled = true;
force force ace_hitreactions_minDamageToTrigger = 0.1;
ace_inventory_inventoryDisplaySize = 0;
force force ace_laser_dispersionCount = 2;
force ace_laser_showLaserOnMap = 1;
force ace_marker_flags_placeAnywhere = false;
force force ace_microdagr_mapDataAvailable = 2;
force force ace_microdagr_waypointPrecision = 3;
force force ace_noradio_enabled = true;
ace_optionsmenu_showNewsOnMainMenu = true;
force force ace_overpressure_distanceCoefficient = 1;
force ace_parachute_failureChance = 0;
ace_parachute_hideAltimeter = true;
ace_tagging_quickTag = 1;

// ACE User Interface
force ace_ui_allowSelectiveUI = true;
ace_ui_ammoCount = false;
ace_ui_ammoType = true;
ace_ui_commandMenu = true;
ace_ui_firingMode = true;
ace_ui_groupBar = false;
ace_ui_gunnerAmmoCount = true;
ace_ui_gunnerAmmoType = true;
ace_ui_gunnerFiringMode = true;
ace_ui_gunnerLaunchableCount = true;
ace_ui_gunnerLaunchableName = true;
ace_ui_gunnerMagCount = true;
ace_ui_gunnerWeaponLowerInfoBackground = true;
ace_ui_gunnerWeaponName = true;
ace_ui_gunnerWeaponNameBackground = true;
ace_ui_gunnerZeroing = true;
ace_ui_magCount = true;
ace_ui_soldierVehicleWeaponInfo = true;
ace_ui_staminaBar = true;
ace_ui_stance = true;
ace_ui_throwableCount = true;
ace_ui_throwableName = true;
ace_ui_vehicleAltitude = true;
ace_ui_vehicleCompass = true;
ace_ui_vehicleDamage = true;
ace_ui_vehicleFuelBar = true;
ace_ui_vehicleInfoBackground = true;
ace_ui_vehicleName = true;
ace_ui_vehicleNameBackground = true;
ace_ui_vehicleRadar = true;
ace_ui_vehicleSpeed = true;
ace_ui_weaponLowerInfoBackground = true;
ace_ui_weaponName = true;
ace_ui_weaponNameBackground = true;
ace_ui_zeroing = true;

// ACE Vehicle Lock
force force ace_vehiclelock_defaultLockpickStrength = 10;
force force ace_vehiclelock_lockVehicleInventory = true;
force force ace_vehiclelock_vehicleStartingLockState = -1;

// ACE Vehicles
force ace_novehicleclanlogo_enabled = false;
ace_vehicles_hideEjectAction = true;
force force ace_vehicles_keepEngineRunning = false;
force ace_vehicles_speedLimiterStep = 5;
force ace_viewports_enabled = true;

// ACE View Distance Limiter
force ace_viewdistance_enabled = false;
force ace_viewdistance_limitViewDistance = 10000;
ace_viewdistance_objectViewDistanceCoeff = 0;
ace_viewdistance_viewDistanceAirVehicle = 0;
ace_viewdistance_viewDistanceLandVehicle = 0;
ace_viewdistance_viewDistanceOnFoot = 0;

// ACE View Restriction
force force acex_viewrestriction_mode = 1;
force acex_viewrestriction_modeSelectiveAir = 0;
force acex_viewrestriction_modeSelectiveFoot = 0;
force acex_viewrestriction_modeSelectiveLand = 0;
force acex_viewrestriction_modeSelectiveSea = 0;
acex_viewrestriction_preserveView = false;

// ACE Volume
acex_volume_enabled = true;
acex_volume_fadeDelay = 1;
acex_volume_lowerInVehicles = false;
acex_volume_reduction = 9;
acex_volume_remindIfLowered = false;
acex_volume_showNotification = true;

// ACE Weapons
ace_common_persistentLaserEnabled = false;
force force ace_laserpointer_enabled = true;
ace_reload_displayText = true;
ace_reload_showCheckAmmoSelf = false;
ace_weaponselect_displayText = true;

// ACE Weather
force force ace_weather_enabled = false;
ace_weather_showCheckAirTemperature = true;
force force ace_weather_updateInterval = 60;
force force ace_weather_windSimulation = false;

// ACE Wind Deflection
force force ace_winddeflection_enabled = false;
force force ace_winddeflection_simulationInterval = 0.05;
force force ace_winddeflection_vehicleEnabled = false;

// ACE Zeus
force ace_zeus_autoAddObjects = false;
force ace_zeus_canCreateZeus = 0;
force ace_zeus_radioOrdnance = false;
force ace_zeus_remoteWind = false;
force ace_zeus_revealMines = 0;
force ace_zeus_zeusAscension = false;
force ace_zeus_zeusBird = false;

// Backpack On Chest
force bocr_main_disabled = false;
force bocr_main_walk = true;

// Blastcore Murr Edition
WarFXPE_BlastWave = 1;
WarFXPE_HeatHaze = true;
WarFXPE_WeatherEffects = true;

// Bundeswehr
BWA3_Leopard_ClocknumbersDir_Commander = false;
BWA3_NaviPad_showMembers = true;
BWA3_Puma_ClocknumbersDir_Commander = false;
BWA3_Puma_ClocknumbersDir_Gunner = false;

// Community Base Addons
cba_diagnostic_ConsoleIndentType = -1;
force cba_diagnostic_watchInfoRefreshRate = 0.2;
cba_disposable_dropUsedLauncher = 2;
force cba_disposable_replaceDisposableLauncher = true;
cba_events_repetitionMode = 1;
force cba_network_loadoutValidation = 0;
cba_optics_usePipOptics = true;
cba_ui_notifyLifetime = 4;
cba_ui_StorePasswords = 1;

// DUI - Squad Radar - Indicators
diwako_dui_indicators_fov_scale = false;
diwako_dui_indicators_icon_buddy = true;
diwako_dui_indicators_icon_leader = true;
diwako_dui_indicators_icon_medic = true;
diwako_dui_indicators_range = 20;
diwako_dui_indicators_range_scale = false;
diwako_dui_indicators_show = true;
diwako_dui_indicators_size = 1;
diwako_dui_indicators_style = "standard";
diwako_dui_indicators_useACENametagsRange = true;

// DUI - Squad Radar - Main
diwako_dui_ace_hide_interaction = true;
diwako_dui_colors = "standard";
diwako_dui_font = "RobotoCondensed";
diwako_dui_icon_style = "standard";
diwako_dui_main_hide_ui_by_default = false;
diwako_dui_main_squadBlue = [0,0,1,1];
diwako_dui_main_squadGreen = [0,1,0,1];
diwako_dui_main_squadMain = [1,1,1,1];
diwako_dui_main_squadRed = [1,0,0,1];
diwako_dui_main_squadYellow = [1,1,0,1];

// DUI - Squad Radar - Radar
diwako_dui_compass_hide_alone_group = false;
diwako_dui_compass_hide_blip_alone_group = false;
diwako_dui_compass_icon_scale = 1;
diwako_dui_compass_opacity = 1;
diwako_dui_compass_style = ["\z\diwako_dui\addons\radar\UI\compass_styles\standard\compass_limited.paa","\z\diwako_dui\addons\radar\UI\compass_styles\standard\compass.paa"];
diwako_dui_compassRange = 35;
diwako_dui_compassRefreshrate = 0;
diwako_dui_dir_showMildot = false;
diwako_dui_dir_size = 1.25;
diwako_dui_distanceWarning = 3;
diwako_dui_enable_compass = true;
diwako_dui_enable_compass_dir = 1;
diwako_dui_enable_occlusion = true;
diwako_dui_enable_occlusion_cone = 360;
diwako_dui_hudScaling = 1.33333;
diwako_dui_namelist = true;
diwako_dui_namelist_bg = 0;
diwako_dui_namelist_only_buddy_icon = false;
diwako_dui_namelist_size = 1.5396;
diwako_dui_namelist_text_shadow = 2;
diwako_dui_namelist_width = 215;
diwako_dui_radar_ace_finger = true;
diwako_dui_radar_group_by_vehicle = false;
diwako_dui_radar_leadingZeroes = false;
diwako_dui_radar_namelist_hideWhenLeader = false;
diwako_dui_radar_namelist_vertical_spacing = 0.75;
diwako_dui_radar_occlusion_fade_time = 10;
diwako_dui_radar_pointer_color = [1,0.5,0,1];
diwako_dui_radar_pointer_style = "standard";
force diwako_dui_radar_sortType = "none";
force diwako_dui_radar_sqlFirst = false;
diwako_dui_radar_trackingColor = [0.93,0.26,0.93,1];
diwako_dui_reset_ui_pos = false;
diwako_dui_use_layout_editor = false;


// Enhanced Movement Rework
force force emr_main_allowMidairClimbing = true;
force emr_main_animSpeedCoef = 1;
force emr_main_animSpeedStaminaCoef = 0.4;
force emr_main_assistDuty = 1.5;
force emr_main_assistHeight = 1;
force emr_main_blacklistStr = "";
force force emr_main_climbingEnabled = true;
force force emr_main_climbOnDuty = 3.4;
force force emr_main_climbOverDuty = 3;
force force emr_main_dropDuty = 0.7;
emr_main_dropViewElevation = -0.7;
force force emr_main_enableWalkableSurface = true;
force force emr_main_enableWeightCheck = true;
emr_main_hintType = 2;
force force emr_main_jumpDuty = 1;
force emr_main_jumpForwardVelocity = 1.2;
force force emr_main_jumpingEnabled = true;
force force emr_main_jumpingLoadCoefficient = 1;
force force emr_main_jumpVelocity = 3.4;
force force emr_main_maxClimbHeight = 2.6;
force force emr_main_maxDropHeight = 5;
force force emr_main_maxWeightClimb1 = 100;
force force emr_main_maxWeightClimb2 = 85;
force force emr_main_maxWeightClimb3 = 60;
force force emr_main_maxWeightJump = 100;
force force emr_main_preventHighVaulting = false;
force force emr_main_staminaCoefficient = 1;
force emr_main_whitelistStr = "";
force emr_main_yeetCoefficient = 1.4;

// F/A-18
js_jc_fa18_advancedStart = false;
js_jc_fa18_atflirRequire = true;
js_jc_fa18_canopyLoss = false;
js_jc_fa18_cursorSensitivity = 1;
js_jc_fa18_interactCursor = false;
js_jc_fa18_interactionRadiusMod = 1;
js_jc_fa18_mav_tdcDepressRequiredForMove = false;
js_jc_fa18_showLabels = true;

// GRAD CaptiveWalkingAnimation
force force grad_captiveWalking_functions_allowFreeing = true;
force force grad_captiveWalking_functions_allowRunning = false;
force force grad_captiveWalking_functions_allowWalkingWhileCaptiv = true;
force force grad_captiveWalking_functions_disableEscorting = false;
force force grad_captiveWalking_functions_freeingTime = 35;

// GRAD Trenches
force grad_trenches_functions_allowBigEnvelope = true;
force grad_trenches_functions_allowCamouflage = true;
force grad_trenches_functions_allowDigging = true;
force grad_trenches_functions_allowEffects = true;
force grad_trenches_functions_allowGiantEnvelope = true;
force grad_trenches_functions_allowHitDecay = true;
force grad_trenches_functions_allowLongEnvelope = true;
force grad_trenches_functions_allowShortEnvelope = true;
force grad_trenches_functions_allowSmallEnvelope = true;
force grad_trenches_functions_allowTrenchDecay = false;
force grad_trenches_functions_allowVehicleEnvelope = true;
force grad_trenches_functions_bigEnvelopeDamageMultiplier = 2;
force grad_trenches_functions_bigEnvelopeDigTime = 40;
force grad_trenches_functions_bigEnvelopeRemovalTime = -1;
force grad_trenches_functions_buildFatigueFactor = 1;
force grad_trenches_functions_camouflageRequireEntrenchmentTool = true;
force grad_trenches_functions_createTrenchMarker = false;
force grad_trenches_functions_decayTime = 1800;
force grad_trenches_functions_giantEnvelopeDamageMultiplier = 1;
force grad_trenches_functions_giantEnvelopeDigTime = 90;
force grad_trenches_functions_giantEnvelopeRemovalTime = -1;
force grad_trenches_functions_hitDecayMultiplier = 1;
force grad_trenches_functions_LongEnvelopeDigTime = 100;
force grad_trenches_functions_LongEnvelopeRemovalTime = -1;
force grad_trenches_functions_shortEnvelopeDamageMultiplier = 2;
force grad_trenches_functions_shortEnvelopeDigTime = 15;
force grad_trenches_functions_shortEnvelopeRemovalTime = -1;
force grad_trenches_functions_smallEnvelopeDamageMultiplier = 3;
force grad_trenches_functions_smallEnvelopeDigTime = 30;
force grad_trenches_functions_smallEnvelopeRemovalTime = -1;
force grad_trenches_functions_stopBuildingAtFatigueMax = true;
force grad_trenches_functions_timeoutToDecay = 7200;
force grad_trenches_functions_vehicleEnvelopeDamageMultiplier = 1;
force grad_trenches_functions_vehicleEnvelopeDigTime = 120;
force grad_trenches_functions_vehicleEnvelopeRemovalTime = -1;

// Improved Melee System (Client Settings)
IMS_CustomCamer_Y = 3;
IMS_CustomCameraUsedByUserAllowed = true;
IMS_EnablePlayerSounds = true;
IMS_HudCoordinate_X = 0.01;
IMS_HudCoordinate_Y = 0.9;
IMS_ShowHealthHud = true;

// Improved Melee System (Server Settings)
force force IMS_AddKnifeToUnit = true;
force force IMS_BayonetDistance = "6";
force force IMS_BayonetOnAI = false;
force force IMS_BluntWeapon = true;
force force IMS_CustomAIHEALTH = "2";
force force IMS_DamageMultiplierParam = "1";
force IMS_DamageMultiplierParamPlayer = "1";
force force IMS_ExecutionChanceParametr = "20";
force IMS_isFistsAllowd = true;
force force IMS_isHumansCanHitSM = false;
force force IMS_isImsCanHitAllies = false;
force IMS_isKickButtInstaKill = true;
force force IMS_isStaticDeaths = true;
force force IMS_RifleDodgeSet = false;
force force IMS_StealthAI_Ears = 15;
force force IMS_StealthAI_Eyes = 40;
force IMS_WBK_CUSTOMCAMSERVER = false;

// KAT - ADV Medical: Airway
force kat_airway_Accuvac_time = 8;
force kat_airway_CancelRecoveryPosition_Time = 6;
force kat_airway_CheckAirway_time = 2;
force kat_airway_checkbox_puking_sound = true;
force kat_airway_Colored_logs = true;
force kat_airway_enable = true;
force kat_airway_Guedeltubus_time = 6;
force kat_airway_Larynxtubus_time = 3;
force kat_airway_medLvl_Accuvac = 1;
force kat_airway_medLvl_Guedeltubus = 0;
force kat_airway_medLvl_Larynxtubus = 1;
force kat_airway_occlusion_repeatTimer = 60;
force kat_airway_Overstretch_time = 3;
force kat_airway_probability_headturning = 50;
force kat_airway_probability_obstruction = 50;
force kat_airway_probability_occluded = 50;
force kat_airway_RecoveryPosition_Time = 6;
force kat_airway_string_exit = "";
force kat_airway_TurnAround_time = 3;

// KAT - ADV Medical: Breathing
force kat_breathing_deterioratingPneumothorax_chance = 10;
force kat_breathing_deterioratingPneumothorax_countdown = 120;
force kat_breathing_enable = true;
force kat_breathing_enable_selfChestseal = 0;
force kat_breathing_enableCyanosis = true;
force kat_breathing_hemopneumothoraxChance = 5;
force kat_breathing_medLvl_Chestseal = 1;
force kat_breathing_medLvl_Cyanosis = 1;
force kat_breathing_medLvl_hemopneumothoraxTreatment = 1;
force kat_breathing_medLvl_Pulseoximeter = 0;
force kat_breathing_mildValue = 70;
force kat_breathing_pneumothorax = 5;
force kat_breathing_pneumothorax_hardcore = false;
force kat_breathing_pneumothoraxDamageThreshold = 0.4;
force kat_breathing_severeValue = 40;
force kat_breathing_showPneumothorax_dupe = false;
force kat_breathing_slightValue = 80;
force kat_breathing_SpO2_dieActive = true;
force kat_breathing_SpO2_dieValue = 40;
force kat_breathing_SpO2_MultiplyNegative = 1;
force kat_breathing_SpO2_MultiplyPositive = 3;
force kat_breathing_SpO2_perfusion = true;
force kat_breathing_SpO2_PerfusionMultiplier = 1;
force kat_breathing_SpO2_unconscious = 75;
force kat_breathing_Stable_spo2 = 85;
force kat_breathing_tensionhemothorax_hardcore = false;

// KAT - ADV Medical: Circulation
force kat_circulation_AdvRhythm = true;
force kat_circulation_AED_BeepsAndCharge = true;
force kat_circulation_AED_MaxChance = 80;
force kat_circulation_AED_MinChance = 40;
force kat_circulation_AED_X_MaxChance = 90;
force kat_circulation_AED_X_MinChance = 45;
force kat_circulation_blood_draw_limit = 3.6;
force kat_circulation_blood_drawTime_250ml = 10;
force kat_circulation_blood_drawTime_500ml = 20;
kat_circulation_bloodgroup = "B_N";
force kat_circulation_bloodGroups = true;
force kat_circulation_CPR_MaxChance_Default = 20;
force kat_circulation_CPR_MaxChance_Doctor = 40;
force kat_circulation_CPR_MaxChance_RegularMedic = 30;
force kat_circulation_CPR_MinChance_Default = 10;
force kat_circulation_CPR_MinChance_Doctor = 20;
force kat_circulation_CPR_MinChance_RegularMedic = 15;
force kat_circulation_DeactMon_whileAED_X = true;
force kat_circulation_distanceLimit_AEDX = 15;
force kat_circulation_enable = false;
force kat_circulation_enable_CPR_Chances = true;
force kat_circulation_enable_selfBloodDraw = 1;
force kat_circulation_medLvl_AED = 1;
force kat_circulation_medLvl_AED_X = 1;
force kat_circulation_timeLimit_AEDX = 1800;
force kat_circulation_useLocation_AED = 0;

// KAT - ADV Medical: Misc
force kat_misc_arsenalMedCategory = true;
force kat_misc_enable = true;
force kat_misc_incompatibilityWarning = true;

// KAT - ADV Medical: Pharmacy
force kat_pharma_blockChance = 20;
force kat_pharma_carbonateChance = 100;
force kat_pharma_coagulation = true;
force kat_pharma_ivCheckLimbDamage = false;
force kat_pharma_IVdrop = 300;
force kat_pharma_IVdropEnable = true;
force kat_pharma_IVreuse = false;
force kat_pharma_kidneyAction = false;
force kat_pharma_maxStack = 5;
force kat_pharma_MedicationsRequireInsIV = false;
force kat_pharma_medLvl_Amiodarone = 0;
force kat_pharma_medLvl_ApplyIO = 0;
force kat_pharma_medLvl_ApplyIV = 0;
force kat_pharma_medLvl_Atropine = 0;
force kat_pharma_medLvl_Carbonate = 0;
force kat_pharma_medLvl_EACA = 0;
force kat_pharma_medLvl_Etomidate = 0;
force kat_pharma_medLvl_Fentanyl = 0;
force kat_pharma_medLvl_Flumezenil = 0;
force kat_pharma_medLvl_Ketamine = 0;
force kat_pharma_medLvl_Lidocaine = 0;
force kat_pharma_medLvl_Lorazepam = 0;
force kat_pharma_medLvl_Nalbuphine = 0;
force kat_pharma_medLvl_Naloxone = 0;
force kat_pharma_medLvl_Nitroglycerin = 0;
force kat_pharma_medLvl_Norepinephrine = 0;
force kat_pharma_medLvl_Phenylephrine = 0;
force kat_pharma_medLvl_Reorientation = 0;
force kat_pharma_medLvl_TXA = 0;
force kat_pharma_Reorientation_Enable = true;
force kat_pharma_Reorientation_Slap = true;
force kat_pharma_reorientationChance = 50;
force kat_pharma_RequireInsIV = true;
force kat_pharma_treatmentTime_Amiodarone = 7;
force kat_pharma_treatmentTime_ApplyIO = 7;
force kat_pharma_treatmentTime_ApplyIV = 7;
force kat_pharma_treatmentTime_Atropine = 7;
force kat_pharma_treatmentTime_Carbonate = 7;
force kat_pharma_treatmentTime_EACA = 7;
force kat_pharma_treatmentTime_Etomidate = 2;
force kat_pharma_treatmentTime_Fentanyl = 7;
force kat_pharma_treatmentTime_Flumazenil = 2;
force kat_pharma_treatmentTime_Ketamine = 7;
force kat_pharma_treatmentTime_Lidocaine = 7;
force kat_pharma_treatmentTime_Lorazepam = 2;
force kat_pharma_treatmentTime_Nalbuphine = 7;
force kat_pharma_treatmentTime_Naloxone = 7;
force kat_pharma_treatmentTime_Nitroglycerin = 7;
force kat_pharma_treatmentTime_Norepinephrine = 7;
force kat_pharma_treatmentTime_Phenylephrine = 7;
force kat_pharma_treatmentTime_Reorientation = 1;
force kat_pharma_treatmentTime_TXA = 7;

// KAT - ADV Medical: Surgery
force kat_surgery_BreathCheck_MedLevel = 0;
force kat_surgery_BreathCheck_Time = 2;
force kat_surgery_closedLocation = 0;
force kat_surgery_closedReduction_MedLevel = 0;
force kat_surgery_closedTime = 10;
force kat_surgery_compoundChance = 30;
force kat_surgery_debrideTime = 20;
force kat_surgery_enable_fracture = false;
force kat_surgery_enable_selfCheckFracture = 1;
force kat_surgery_etomidateTime = 45;
force kat_surgery_fractureCheck_MedLevel = 0;
force kat_surgery_fractureCheck_Time = 10;
force kat_surgery_incisionTime = 10;
force kat_surgery_intermediateTime = 8;
force kat_surgery_npwtTime = 20;
force kat_surgery_openTime = 15;
force kat_surgery_simpleChance = 60;
force kat_surgery_surgicalAction_MedLevel = 0;
force kat_surgery_surgicalLocation = 0;
force kat_surgery_uncon_requieredForActions = false;

// LAMBS Danger
force lambs_danger_cqbRange = 60;
force lambs_danger_disableAIAutonomousManoeuvres = false;
force lambs_danger_disableAIDeployStaticWeapons = false;
force lambs_danger_disableAIFindStaticWeapons = false;
force lambs_danger_disableAIHideFromTanksAndAircraft = false;
force lambs_danger_disableAIPlayerGroup = true;
force lambs_danger_disableAIPlayerGroupReaction = true;
force lambs_danger_disableAutonomousFlares = false;
force lambs_danger_disableAutonomousSmokeGrenades = false;
force lambs_danger_panicChance = 0.1;

// LAMBS Danger Eventhandlers
force lambs_eventhandlers_ExplosionEventHandlerEnabled = false;
force lambs_eventhandlers_ExplosionReactionTime = 9;

// LAMBS Danger WP
force lambs_wp_autoAddArtillery = false;

// LAMBS Main
force lambs_main_combatShareRange = 200;
force lambs_main_debug_drawAllUnitsInVehicles = false;
force lambs_main_debug_Drawing = false;
force lambs_main_debug_FSM = false;
force lambs_main_debug_FSM_civ = false;
force lambs_main_debug_functions = false;
force lambs_main_debug_RenderExpectedDestination = false;
force lambs_main_disableAICallouts = false;
force lambs_main_disableAIDodge = false;
force lambs_main_disableAIFleeing = false;
force lambs_main_disableAIGestures = false;
force lambs_main_disableAutonomousMunitionSwitching = false;
force lambs_main_disablePlayerGroupSuppression = true;
force lambs_main_indoorMove = 0.5;
force lambs_main_maxRevealValue = 1;
force lambs_main_minFriendlySuppressionDistance = 5;
force lambs_main_minObstacleProximity = 5;
force lambs_main_minSuppressionRange = 50;
force lambs_main_radioBackpack = 2000;
force lambs_main_radioDisabled = false;
force lambs_main_radioEast = 500;
force lambs_main_radioGuer = 500;
force lambs_main_radioShout = 100;
force lambs_main_radioWest = 500;

// NIArms
force niarms_accswitch = true;
force niarms_magSwitch = true;

// No More Aircraft Bouncing
force NMAB_setting_classExclusionsStr = "";
force NMAB_setting_pfxHelicopters = true;
force NMAB_setting_pfxPlanes = true;

// Simple Suppress
force simplesuppress_suppress_checkLOS = false;
force simplesuppress_suppress_overlayFadeoutTime = 2;
force simplesuppress_suppress_overlayOpacity = 0.9;
force simplesuppress_suppress_overlayTexture = 0;
force simplesuppress_suppress_projectileMaxDistance = 5;
force simplesuppress_suppress_shooterMinDistance = 0;

// TFAR - Clientside settings
force TFAR_curatorCamEars = true;
TFAR_default_radioVolume = 5;
TFAR_intercomDucking = 0.2;
TFAR_intercomVolume = 0.1;
force TFAR_moveWhileTabbedOut = false;
force TFAR_noAutomoveSpectator = false;
force TFAR_oldVolumeHint = false;
TFAR_pluginTimeout = 4;
TFAR_PosUpdateMode = 0.2;
force TFAR_showChannelChangedHint = true;
force TFAR_ShowDiaryRecord = false;
force TFAR_showTransmittingHint = true;
force TFAR_ShowVolumeHUD = false;
TFAR_tangentReleaseDelay = 0;
TFAR_VolumeHudTransparency = 0.5;
TFAR_volumeModifier_forceSpeech = false;

// TFAR - Global settings
force TFAR_AICanHearPlayer = true;
force TFAR_AICanHearSpeaker = true;
force TFAR_allowDebugging = true;
tfar_core_noTSNotConnectedHint = false;
force TFAR_defaultIntercomSlot = 0;
force TFAR_disableAutoMute = false;
force TFAR_enableIntercom = true;
force TFAR_experimentalVehicleIsolation = true;
force TFAR_fullDuplex = true;
force TFAR_giveLongRangeRadioToGroupLeaders = false;
force TFAR_giveMicroDagrToSoldier = false;
force TFAR_givePersonalRadioToRegularSoldier = false;
force TFAR_globalRadioRangeCoef = 1;
force TFAR_instantiate_instantiateAtBriefing = false;
force TFAR_objectInterceptionEnabled = false;
force TFAR_objectInterceptionStrength = 400;
force tfar_radiocode_east = "_opfor";
force tfar_radiocode_independent = "_independent";
force tfar_radiocode_west = "_bluefor";
force tfar_radioCodesDisabled = true;
force TFAR_SameLRFrequenciesForSide = true;
force TFAR_SameSRFrequenciesForSide = true;
force TFAR_setting_defaultFrequencies_lr_east = "41,42,43,44,45,46,47,48,49";
force TFAR_setting_defaultFrequencies_lr_independent = "41,42,43,44,45,46,47,48,49";
force TFAR_setting_defaultFrequencies_lr_west = "41,42,43,44,45,46,47,48,49";
force TFAR_setting_defaultFrequencies_sr_east = "101,102,103,104,105,106,107,108,109";
force TFAR_setting_defaultFrequencies_sr_independent = "101,102,103,104,105,106,107,108,109";
force TFAR_setting_defaultFrequencies_sr_west = "101,102,103,104,105,106,107,108,109";
force TFAR_setting_DefaultRadio_Airborne_east = "TFAR_mr6000l";
force TFAR_setting_DefaultRadio_Airborne_Independent = "TFAR_anarc164";
force TFAR_setting_DefaultRadio_Airborne_West = "TFAR_anarc210";
force TFAR_setting_DefaultRadio_Backpack_east = "TFAR_mr3000";
force TFAR_setting_DefaultRadio_Backpack_Independent = "TFAR_anprc155";
force TFAR_setting_DefaultRadio_Backpack_west = "TFAR_rt1523g";
force TFAR_setting_DefaultRadio_Personal_east = "TFAR_fadak";
force TFAR_setting_DefaultRadio_Personal_Independent = "TFAR_anprc154";
force TFAR_setting_DefaultRadio_Personal_West = "TFAR_anprc152";
force TFAR_setting_DefaultRadio_Rifleman_East = "TFAR_fadak";
force TFAR_setting_DefaultRadio_Rifleman_Independent = "TFAR_anprc154";
force TFAR_setting_DefaultRadio_Rifleman_West = "TFAR_anprc152";
force TFAR_spectatorCanHearEnemyUnits = false;
force TFAR_spectatorCanHearFriendlies = true;
force TFAR_takingRadio = 1;
force TFAR_Teamspeak_Channel_Name = "TaskForceRadio";
force TFAR_Teamspeak_Channel_Password = "123";
force tfar_terrain_interception_coefficient = 7;
force TFAR_voiceCone = true;

// TFI AI
force SFSM_Allow_HC = false;
force SFSM_allowDodging = false;
force SFSM_allowFlinching = false;
force SFSM_AtSpecHuntVehicles = false;
force SFSM_breakCoverOnHit = false;
force SFSM_CQBdistance = 30;
force SFSM_CQBunitCap = 6;
force SFSM_Debugger = false;
force SFSM_disableSoldierFSM = true;
force SFSM_DodgeCoolDown = 10;
force SFSM_DodgeDistance = 60;
force SFSM_dodgeIndoors = false;
force SFSM_DodgeTimer = 40;
force SFSM_emergencyRearm = false;
force SFSM_ExcludeZcommand = false;
force SFSM_explosionCoverRad = 120;
force SFSM_FlinchCoolDown = 5;
force SFSM_flinchStopDodge = false;
force SFSM_hearingDistance = 250;
force SFSM_hearingHide = false;
force SFSM_hideFromVehicles = false;
force SFSM_hidingTimeOut = 30;
force SFSM_hijackVehicles = false;
force SFSM_houseDemolition = false;
force SFSM_KnowledgeToFight = 0.1;
force SFSM_legHealingOn = false;
force SFSM_mgSuppressClusters = false;
force SFSM_noCoverPanic = false;
force SFSM_overrunDistance = 40;
force SFSM_panicCoef = 0.5;
force SFSM_PlayerGrpDodge = false;
force SFSM_ProneTreshHold = 0.7;
force SFSM_reactFireCoolDown = 180;
force SFSM_rpgHouse = false;
force SFSM_RpsDodgeTrigger = 4;
force SFSM_sprintSpeed = 1.1;
force SFSM_stayCoverPosTime = 20;
force SFSM_Use_HC = false;
force TFI_AI_CBA_disAICommand = true;

// TFI Animation
force TFI_Anim_CBA_disHitReaction = false;
force TFI_Anim_CBA_duckChance = 0.25;
force TFI_Anim_CBA_duckRange = 3;
force TFI_Anim_CBA_hitChance = 0.15;
force TFI_Anim_CBA_playerHit = false;
force tsp_cba_animate_Aggressive 1 = true;
force tsp_cba_animate_Aggressive 2 = true;
force tsp_cba_animate_Agreeing 1 = true;
force tsp_cba_animate_Agreeing 2 = true;
force tsp_cba_animate_Angery = true;
force tsp_cba_animate_Approximate 1 = true;
force tsp_cba_animate_Approximate 2 = true;
force tsp_cba_animate_Approximate 3 = true;
force tsp_cba_animate_Attention 1 = true;
force tsp_cba_animate_Attention 2 = true;
force tsp_cba_animate_Attention 3 = true;
force tsp_cba_animate_Attention 4 = true;
force tsp_cba_animate_Attention 5 = true;
force tsp_cba_animate_Attention 6 = true;
force tsp_cba_animate_Bird = true;
force tsp_cba_animate_Clapping = true;
force tsp_cba_animate_Confused = true;
force tsp_cba_animate_Contact 1 = true;
force tsp_cba_animate_Contact 2 = true;
force tsp_cba_animate_Crazy = true;
force tsp_cba_animate_Crouch = true;
force tsp_cba_animate_Crouch Thumbup = true;
force tsp_cba_animate_Dab 1 = true;
force tsp_cba_animate_Dab 2 = true;
force tsp_cba_animate_Dab 3 = true;
force tsp_cba_animate_Dead 1 = true;
force tsp_cba_animate_Dead 2 = true;
force tsp_cba_animate_Defensive 1 = true;
force tsp_cba_animate_Defensive 2 = true;
force tsp_cba_animate_Disagreeing 1 = true;
force tsp_cba_animate_Disagreeing 2 = true;
force tsp_cba_animate_Disagreeing 3 = true;
force tsp_cba_animate_Dismissing 1 = true;
force tsp_cba_animate_Dismissing 2 = true;
force tsp_cba_animate_door = true;
force tsp_cba_animate_Drake No = true;
force tsp_cba_animate_Drake Yes = true;
force tsp_cba_animate_Drunk = true;
force tsp_cba_animate_Dubstep = true;
force tsp_cba_animate_Dubstep Pop = true;
force tsp_cba_animate_Duo (Ivan) = true;
force tsp_cba_animate_Duo (Stefan) = true;
force tsp_cba_animate_dynamicReadyBush = true;
force tsp_cba_animate_dynamicReadyFriend = 2;
force tsp_cba_animate_dynamicReadyFriendAngle = 25;
force tsp_cba_animate_dynamicReadyObject = 1.8;
force tsp_cba_animate_dynamicReadyPoll = 0.1;
force tsp_cba_animate_dynamicReadyVertical = -0.1;
force tsp_cba_animate_Emergency Stop = true;
force tsp_cba_animate_Engines Off = true;
force tsp_cba_animate_Engines On = true;
force tsp_cba_animate_Facepalm = true;
force tsp_cba_animate_Facepalm 1 = true;
force tsp_cba_animate_Facepalm 2 = true;
force tsp_cba_animate_Facepalm 3 = true;
force tsp_cba_animate_Facepalm 4 = true;
force tsp_cba_animate_Facepalm 5 = true;
force tsp_cba_animate_Finger Pistol = true;
force tsp_cba_animate_friendsAreObjects = true;
force tsp_cba_animate_High Five = true;
force tsp_cba_animate_HipHop = true;
force tsp_cba_animate_Horns = true;
force tsp_cba_animate_I Want You = true;
force tsp_cba_animate_Idle 1 = true;
force tsp_cba_animate_Idle 10 = true;
force tsp_cba_animate_Idle 11 = true;
force tsp_cba_animate_Idle 12 = true;
force tsp_cba_animate_Idle 13 = true;
force tsp_cba_animate_Idle 14 = true;
force tsp_cba_animate_Idle 15 = true;
force tsp_cba_animate_Idle 16 = true;
force tsp_cba_animate_Idle 17 = true;
force tsp_cba_animate_Idle 18 = true;
force tsp_cba_animate_Idle 19 = true;
force tsp_cba_animate_Idle 2 = true;
force tsp_cba_animate_Idle 20 = true;
force tsp_cba_animate_Idle 3 = true;
force tsp_cba_animate_Idle 4 = true;
force tsp_cba_animate_Idle 5 = true;
force tsp_cba_animate_Idle 6 = true;
force tsp_cba_animate_Idle 7 = true;
force tsp_cba_animate_Idle 8 = true;
force tsp_cba_animate_Idle 9 = true;
force tsp_cba_animate_Inspect Weapon = true;
force tsp_cba_animate_Jackoff = true;
force tsp_cba_animate_Kata = true;
force tsp_cba_animate_Kiss = true;
force tsp_cba_animate_Launch = true;
force tsp_cba_animate_Left = true;
force tsp_cba_animate_Mahalo = true;
force tsp_cba_animate_map = true;
force tsp_cba_animate_Metal = true;
force tsp_cba_animate_Nightclub = true;
force tsp_cba_animate_Nod No = true;
force tsp_cba_animate_Nod Yes = true;
force tsp_cba_animate_nvg = true;
force tsp_cba_animate_Ok = true;
force tsp_cba_animate_Panic = true;
force tsp_cba_animate_Paper = true;
force tsp_cba_animate_Peace 1 = true;
force tsp_cba_animate_Peace 2 = true;
force tsp_cba_animate_Pissing = true;
force tsp_cba_animate_Play Dead = true;
force tsp_cba_animate_Point Back = true;
force tsp_cba_animate_Point Down = true;
force tsp_cba_animate_Point Front = true;
force tsp_cba_animate_Point Left = true;
force tsp_cba_animate_Point Right = true;
force tsp_cba_animate_Point Up = true;
force tsp_cba_animate_Pushups = true;
force tsp_cba_animate_Right = true;
force tsp_cba_animate_Robo = true;
force tsp_cba_animate_Rock = true;
force tsp_cba_animate_Russian = true;
force tsp_cba_animate_Sad = true;
force tsp_cba_animate_Satisfied = true;
force tsp_cba_animate_Scissors = true;
force tsp_cba_animate_Scratch = true;
force tsp_cba_animate_Selfie 1 = true;
force tsp_cba_animate_Selfie 2 = true;
force tsp_cba_animate_Shouting = true;
force tsp_cba_animate_Sleeping = true;
force tsp_cba_animate_Sleepy = true;
force tsp_cba_animate_Slow = true;
force tsp_cba_animate_Smile = true;
force tsp_cba_animate_Smirking = true;
force tsp_cba_animate_Sneeze 1 = true;
force tsp_cba_animate_Sneeze 2 = true;
force tsp_cba_animate_Static 1 = true;
force tsp_cba_animate_Static 10 = true;
force tsp_cba_animate_Static 11 = true;
force tsp_cba_animate_Static 12 = true;
force tsp_cba_animate_Static 13 = true;
force tsp_cba_animate_Static 14 = true;
force tsp_cba_animate_Static 15 = true;
force tsp_cba_animate_Static 16 = true;
force tsp_cba_animate_Static 17 = true;
force tsp_cba_animate_Static 18 = true;
force tsp_cba_animate_Static 19 = true;
force tsp_cba_animate_Static 2 = true;
force tsp_cba_animate_Static 20 = true;
force tsp_cba_animate_Static 21 = true;
force tsp_cba_animate_Static 22 = true;
force tsp_cba_animate_Static 23 = true;
force tsp_cba_animate_Static 24 = true;
force tsp_cba_animate_Static 25 = true;
force tsp_cba_animate_Static 3 = true;
force tsp_cba_animate_Static 4 = true;
force tsp_cba_animate_Static 5 = true;
force tsp_cba_animate_Static 6 = true;
force tsp_cba_animate_Static 7 = true;
force tsp_cba_animate_Static 8 = true;
force tsp_cba_animate_Static 9 = true;
force tsp_cba_animate_Stefan = true;
force tsp_cba_animate_Stop = true;
force tsp_cba_animate_Straight = true;
force tsp_cba_animate_Suffering = true;
force tsp_cba_animate_Suicide = true;
force tsp_cba_animate_Surrender 1 = true;
force tsp_cba_animate_Surrender 2 = true;
force tsp_cba_animate_Talking = true;
force tsp_cba_animate_Think = true;
force tsp_cba_animate_Tighten Shoelace = true;
force tsp_cba_animate_Unconscious = true;
force tsp_cba_animate_walk = true;
force tsp_cba_animate_Warming Hands = true;
force tsp_cba_animate_Wave 1 = true;
force tsp_cba_animate_Wave 2 = true;
force tsp_cba_animate_Wave 3 = true;
force tsp_cba_animate_Wave 4 = true;
force tsp_cba_animate_Wave 5 = true;
force tsp_cba_animate_Wave 6 = true;
force tsp_cba_animate_Winking L = true;
force tsp_cba_animate_Winking R = true;
force tsp_cba_animate_Yawn 1 = true;
force tsp_cba_animate_Yawn 2 = true;
force tsp_cba_animate_Yawning = true;
force tsp_cba_animate_ZOZO = true;

// TFI Medical
TFI_AFAK_B1 = "ACE_elasticBandage";
TFI_AFAK_B2 = "ACE_packingBandage";
TFI_AFAK_B3 = "ACE_bloodIV";
TFI_AFAK_B4 = "ACE_bloodIV_500";
TFI_AFAK_M1 = "kat_TXA";
TFI_AFAK_M10 = "kat_nitroglycerin";
TFI_AFAK_M11 = "kat_norepinephrine";
TFI_AFAK_M12 = "kat_phenylephrine";
TFI_AFAK_M2 = "ACE_morphine";
TFI_AFAK_M3 = "ACE_epinephrine";
TFI_AFAK_M4 = "ACE_adenosine";
TFI_AFAK_M5 = "kat_Painkiller";
TFI_AFAK_M6 = "kat_amiodarone";
TFI_AFAK_M7 = "kat_atropine";
TFI_AFAK_M8 = "kat_lidocaine";
TFI_AFAK_M9 = "kat_naloxone";
TFI_AFAK_U1 = "ACE_splint";
TFI_AFAK_U2 = "ACE_tourniquet";
TFI_AFAK_U3 = "kat_guedel";
TFI_AFAK_U4 = "kat_IV_16";
TFI_AFAK_U5 = "kat_larynx";
TFI_AFAK_U6 = "kat_chestSeal";
TFI_AFAK_U7 = "kat_aatKit";
TFI_AFAK_U8 = "kat_IO_FAST";
TFI_IFAK_B1 = "ACE_packingBandage";
TFI_IFAK_B2 = "ACE_quikclot";
TFI_IFAK_B3 = "ACE_bloodIV_500";
TFI_IFAK_M1 = "ACE_epinephrine";
TFI_IFAK_M2 = "ACE_morphine";
TFI_IFAK_M3 = "kat_Painkiller";
TFI_IFAK_U1 = "ACE_tourniquet";
TFI_IFAK_U2 = "ACE_splint";
TFI_IFAK_U3 = "kat_IV_16";
TFI_IFAK_U4 = "kat_Pulseoximeter";
TFI_IFAK_U5 = "kat_guedel";

// TFI Platform
force AR_EnableDisableAltRunMGBOLT = true;
force AR_EnableDisableDoubleShiftPress = true;
force LEO_FFF_enableMod = false;
force LEO_FFF_minHeight = 100;
force TFI_cTab_CBA_usage = true;
force TFI_plat_CBA_craterOn = false;
force TFI_plat_CBA_craterSize = 1.5;

// TFI SFX
force TFI_SFX_CBA_attachSnd = true;
force TFI_SFX_CBA_deathSound = true;
force TFI_SFX_CBA_inventorySound = true;
force TFI_SFX_CBA_jumpSound = true;
force TFI_SFX_CBA_mapSound = true;

// TFI VFX
force TFI_envgAce = true;
force TFI_envgBlacklist = "";
TFI_envgEffect = "mwEffect";
force TFI_VFX_allowGcam = true;
force TFI_VFX_hsOn = false;

// Training Magazines
force Silence_TrainingMags = "3";
force Silence_TrainingMags_2 = "5";
force Silence_TrainingMags_3 = "7";

// VET_Unflipping
force vet_unflipping_require_serviceVehicle = false;
force vet_unflipping_require_toolkit = false;
force vet_unflipping_time = 5;
force vet_unflipping_unit_man_limit = 7;
force vet_unflipping_unit_mass_limit = 3000;
force vet_unflipping_vehicle_mass_limit = 100000;

// WebKnight's Zombies
force WBK_ZombiesIsUseBitingAnimation = true;
force WBK_ZombiesIsUseParticleDeathControl = false;
force WBK_ZombiesIsUseStatDeathControl = false;
force WBK_ZommbiesLeaperHealthParam = "120";
force WBK_ZommbiesSmasherHealthParam = "3500";
force WBK_ZommbiesSmasherJumpParam = true;
force WBK_ZommbiesSmasherThrowParam = true;

// ZaD - ACE integration
force zad_ace_int_pillHeal_enable = true;

// Zeus Enhanced
zen_camera_adaptiveSpeed = false;
zen_camera_defaultSpeedCoef = 1;
zen_camera_fastSpeedCoef = 1;
zen_camera_followTerrain = false;
force zen_common_ascensionMessages = false;
force zen_common_autoAddObjects = true;
force zen_common_cameraBird = false;
force zen_common_darkMode = true;
force zen_common_disableGearAnim = true;
zen_common_preferredArsenal = 1;
zen_compat_ace_hideModules = true;
zen_context_menu_enabled = 2;
zen_context_menu_overrideWaypoints = false;
zen_editor_addGroupIcons = false;
zen_editor_declutterEmptyTree = true;
force zen_editor_disableLiveSearch = true;
zen_editor_moveDisplayToEdge = true;
force zen_editor_parachuteSounds = true;
zen_editor_previews_enabled = true;
zen_editor_randomizeCopyPaste = false;
zen_editor_removeWatermark = true;
zen_editor_unitRadioMessages = 0;
zen_placement_enabled = false;
zen_remote_control_cameraExitPosition = 2;
zen_visibility_enabled = false;
zen_vision_enableBlackHot = false;
zen_vision_enableBlackHotGreenCold = false;
zen_vision_enableBlackHotRedCold = false;
zen_vision_enableGreenHotCold = false;
zen_vision_enableNVG = true;
zen_vision_enableRedGreenThermal = false;
zen_vision_enableRedHotCold = false;
zen_vision_enableWhiteHot = true;
zen_vision_enableWhiteHotRedCold = false;

// Zeus Enhanced - Faction Filter
zen_faction_filter_0_BRPMC = true;
zen_faction_filter_0_DVK_TCF = true;
zen_faction_filter_0_LOP_AFR_OPF = true;
zen_faction_filter_0_LOP_AM_OPF = true;
zen_faction_filter_0_LOP_BH = true;
zen_faction_filter_0_LOP_ChDKZ = true;
zen_faction_filter_0_LOP_IRA = true;
zen_faction_filter_0_LOP_ISTS_OPF = true;
zen_faction_filter_0_LOP_NK = true;
zen_faction_filter_0_LOP_SLA = true;
zen_faction_filter_0_LOP_SYR = true;
zen_faction_filter_0_LOP_TKA = true;
zen_faction_filter_0_LOP_US = true;
zen_faction_filter_0_mas_chi_army = true;
zen_faction_filter_0_mas_chi_army_d = true;
zen_faction_filter_0_mas_chi_army_n = true;
zen_faction_filter_0_mas_chi_army_p = true;
zen_faction_filter_0_mas_chi_army_s = true;
zen_faction_filter_0_mas_chi_army_t = true;
zen_faction_filter_0_mas_chi_army_w = true;
zen_faction_filter_0_OPF_F = true;
zen_faction_filter_0_OPF_G_F = true;
zen_faction_filter_0_OPF_GEN_F = true;
zen_faction_filter_0_OPF_R_F = true;
zen_faction_filter_0_OPF_T_F = true;
zen_faction_filter_0_rhs_faction_msv = true;
zen_faction_filter_0_rhs_faction_rva = true;
zen_faction_filter_0_rhs_faction_tv = true;
zen_faction_filter_0_rhs_faction_vdv = true;
zen_faction_filter_0_rhs_faction_vmf = true;
zen_faction_filter_0_rhs_faction_vpvo = true;
zen_faction_filter_0_rhs_faction_vv = true;
zen_faction_filter_0_rhs_faction_vvs = true;
zen_faction_filter_0_rhs_faction_vvs_c = true;
zen_faction_filter_0_rhsgref_faction_chdkz = true;
zen_faction_filter_0_rhsgref_faction_chdkz_groups = true;
zen_faction_filter_0_rhsgref_faction_tla = true;
zen_faction_filter_0_RWR_ru_winter_cat = true;
zen_faction_filter_0_Ryanzombiesfactionopfor = true;
zen_faction_filter_0_TEC_CSAT = true;
zen_faction_filter_0_TEC_CSAT_Navy = true;
zen_faction_filter_0_TEC_CSAT_Pacific = true;
zen_faction_filter_0_TEC_CSAT_SOF = true;
zen_faction_filter_0_WBK_AI = true;
zen_faction_filter_0_WBK_AI_Melee = true;
zen_faction_filter_0_WBK_AI_ZHAMBIES = true;
zen_faction_filter_1_B_FR = true;
zen_faction_filter_1_BLU_CTRG_F = true;
zen_faction_filter_1_BLU_F = true;
zen_faction_filter_1_BLU_G_F = true;
zen_faction_filter_1_BLU_GEN_F = true;
zen_faction_filter_1_BLU_T_F = true;
zen_faction_filter_1_BLU_W_F = true;
zen_faction_filter_1_British_Top = true;
zen_faction_filter_1_BWA3_Faction_Fleck = true;
zen_faction_filter_1_BWA3_Faction_Multi = true;
zen_faction_filter_1_BWA3_Faction_Tropen = true;
zen_faction_filter_1_Canadian_Desert_Top = true;
zen_faction_filter_1_Canadian_Top = true;
zen_faction_filter_1_Czech_Desert_Top = true;
zen_faction_filter_1_Czech_Top = true;
zen_faction_filter_1_DVK_TCF_B = true;
zen_faction_filter_1_German_Desert_Top = true;
zen_faction_filter_1_German_Top = true;
zen_faction_filter_1_Irish_Top = true;
zen_faction_filter_1_Israeli_Top = true;
zen_faction_filter_1_Latvian_Top = true;
zen_faction_filter_1_LOP_AA = true;
zen_faction_filter_1_LOP_CDF = true;
zen_faction_filter_1_LOP_GRE = true;
zen_faction_filter_1_LOP_IA = true;
zen_faction_filter_1_LOP_PESH = true;
zen_faction_filter_1_Norwegian_Top = true;
zen_faction_filter_1_Polish_Top = true;
zen_faction_filter_1_rhs_faction_socom = true;
zen_faction_filter_1_rhs_faction_usaf = true;
zen_faction_filter_1_rhs_faction_usarmy_d = true;
zen_faction_filter_1_rhs_faction_usarmy_wd = true;
zen_faction_filter_1_rhs_faction_usmc_d = true;
zen_faction_filter_1_rhs_faction_usmc_wd = true;
zen_faction_filter_1_rhs_faction_usn = true;
zen_faction_filter_1_rhsgref_faction_cdf_air_b = true;
zen_faction_filter_1_rhsgref_faction_cdf_ground_b = true;
zen_faction_filter_1_rhsgref_faction_cdf_ground_b_groups = true;
zen_faction_filter_1_rhsgref_faction_cdf_ng_b = true;
zen_faction_filter_1_rhsgref_faction_hidf = true;
zen_faction_filter_1_Swedish_Top = true;
zen_faction_filter_1_TF160 = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Airforce_Arctic = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Airforce_Desert = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Airforce_MTP = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Airforce_Temperate = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Airforce_Tropical = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Airforce_Woodland = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Army_Arctic = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Army_Desert = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Army_MTP = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Army_Temperate = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Army_Tropical = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Army_Woodland = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Navy_Arctic = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Navy_Desert = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Navy_MTP = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Navy_Temperate = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Navy_Tropical = true;
zen_faction_filter_1_UK3CB_BAF_Faction_Navy_Woodland = true;
zen_faction_filter_1_USA = true;
zen_faction_filter_1_USMC = true;
zen_faction_filter_1_USN = true;
zen_faction_filter_1_WBK_AI = true;
zen_faction_filter_1_WBK_AI_Melee = true;
zen_faction_filter_1_WBK_AI_ZHAMBIES = true;
zen_faction_filter_2_DEGA_Vehicles_PMC = true;
zen_faction_filter_2_IND_C_F = true;
zen_faction_filter_2_IND_E_F = true;
zen_faction_filter_2_IND_F = true;
zen_faction_filter_2_IND_G_F = true;
zen_faction_filter_2_IND_L_F = true;
zen_faction_filter_2_LOP_AFR = true;
zen_faction_filter_2_LOP_AM = true;
zen_faction_filter_2_LOP_IRAN = true;
zen_faction_filter_2_LOP_ISTS = true;
zen_faction_filter_2_LOP_NAPA = true;
zen_faction_filter_2_LOP_PESH_IND = true;
zen_faction_filter_2_LOP_PMC = true;
zen_faction_filter_2_LOP_RACS = true;
zen_faction_filter_2_LOP_TRK = true;
zen_faction_filter_2_LOP_UA = true;
zen_faction_filter_2_LOP_UKR = true;
zen_faction_filter_2_LOP_UN = true;
zen_faction_filter_2_LOP_UVF = true;
zen_faction_filter_2_rhsgref_faction_cdf_air = true;
zen_faction_filter_2_rhsgref_faction_cdf_ground = true;
zen_faction_filter_2_rhsgref_faction_cdf_ground_groups = true;
zen_faction_filter_2_rhsgref_faction_cdf_ng = true;
zen_faction_filter_2_rhsgref_faction_cdf_ng_groups = true;
zen_faction_filter_2_rhsgref_faction_chdkz_g = true;
zen_faction_filter_2_rhsgref_faction_chdkz_g_groups = true;
zen_faction_filter_2_rhsgref_faction_nationalist = true;
zen_faction_filter_2_rhsgref_faction_nationalist_groups = true;
zen_faction_filter_2_rhsgref_faction_tla_g = true;
zen_faction_filter_2_rhsgref_faction_un = true;
zen_faction_filter_2_RWG = true;
zen_faction_filter_2_Ryanzombiesfaction = true;
zen_faction_filter_2_WBK_AI_ZHAMBIES = true;
zen_faction_filter_3_CIV_F = true;
zen_faction_filter_3_CIV_IDAP_F = true;
zen_faction_filter_3_IND_F = true;
zen_faction_filter_3_IND_L_F = true;
zen_faction_filter_3_LOP_AFR_Civ = true;
zen_faction_filter_3_LOP_CHR_Civ = true;
zen_faction_filter_3_LOP_TAK_Civ = true;
zen_faction_filter_3_xs_categories = true;
