// by Persian MO
_unit = _this select 0;

_random = 80;
_rs = floor(random _random);
if (_rs == 40) then {

_s = selectRandom [

"soundAK\ak1.ogg",
"soundAK\ak2.ogg",
"soundAK\ak3.ogg",
"soundAK\ak4.ogg",
"soundAK\ak5.ogg",
"soundAK\ak6.ogg",
"soundAK\ak7.ogg",
"soundAK\ak8.ogg",
"soundAK\ak9.ogg",
"soundAK\ak10.ogg",
"soundAK\ak11.ogg",
"soundAK\ak12.ogg",
"soundAK\ak13.ogg",
"soundAK\ak14.ogg",
"soundAK\ak15.ogg",
"soundAK\ak16.ogg",
"soundAK\ak17.ogg",
"soundAK\ak18.ogg",
"soundAK\ak19.ogg",
"soundAK\ak20.ogg",
"soundAK\ak21.ogg",
"soundAK\ak22.ogg",
"soundAK\ak23.ogg",
"soundAK\ak24.ogg",
"soundAK\ak25.ogg",
"soundAK\ak26.ogg",
"soundAK\ak27.ogg",
"soundAK\ak28.ogg",
"soundAK\ak29.ogg",
"soundAK\ak30.ogg",
"soundAK\ak31.ogg",
"soundAK\ak31.ogg",
"soundAK\ak33.ogg",
"soundAK\ak34.ogg",
"soundAK\ak35.ogg",
"soundAK\ak36.ogg",
"soundAK\ak37.ogg",
"soundAK\ak38.ogg",
"soundAK\ak39.ogg",
"soundAK\ak40.ogg",
"soundAK\ak41.ogg",
"soundAK\ak42.ogg",
"soundAK\ak43.ogg",
"soundAK\ak44.ogg",
"soundAK\ak45.ogg",
"soundAK\ak46.ogg",
"soundAK\ak47.ogg",
"soundAK\ak48.ogg",
"soundAK\ak49.ogg",
"soundAK\ak50.ogg",
"soundAK\ak51.ogg",
"soundAK\ak52.ogg",
"soundAK\ak53.ogg",
"soundAK\ak54.ogg",
"soundAK\ak55.ogg",
"soundAK\ak56.ogg",
"soundAK\ak57.ogg",
"soundAK\ak58.ogg",
"soundAK\ak59.ogg",
"soundAK\ak60.ogg",
"soundAK\ak61.ogg",
"soundAK\ak62.ogg",
"soundAK\ak63.ogg",
"soundAK\ak64.ogg",
"soundAK\ak65.ogg",
"soundAK\ak66.ogg",
"soundAK\ak67.ogg",
"soundAK\ak68.ogg",
"soundAK\ak69.ogg",
"soundAK\ak70.ogg",
"soundAK\ak71.ogg",
"soundAK\ak72.ogg",
"soundAK\ak73.ogg",
"soundAK\ak74.ogg",
"soundAK\ak75.ogg",
"soundAK\ak76.ogg",
"soundAK\ak77.ogg",
"soundAK\ak78.ogg",
"soundAK\ak79.ogg",
"soundAK\ak80.ogg",
"soundAK\ak81.ogg",
"soundAK\ak82.ogg",
"soundAK\ak83.ogg",
"soundAK\ak84.ogg",
"soundAK\ak85.ogg",
"soundAK\ak86.ogg",
"soundAK\ak87.ogg",
"soundAK\ak88.ogg",
"soundAK\ak89.ogg",
"soundAK\ak90.ogg",
"soundAK\ak91.ogg",
"soundAK\ak92.ogg",
"soundAK\ak93.ogg",
"soundAK\ak94.ogg",
"soundAK\ak95.ogg",
"soundAK\ak96.ogg",
"soundAK\ak97.ogg",
"soundAK\ak98.ogg",
"soundAK\ak99.ogg",
"soundAK\ak100.ogg",
"soundAK\ak101.ogg",
"soundAK\ak102.ogg",
"soundAK\ak103.ogg",
"soundAK\ak104.ogg",
"soundAK\ak105.ogg",
"soundAK\ak106.ogg",
"soundAK\ak107.ogg",
"soundAK\ak108.ogg",
"soundAK\ak109.ogg",
"soundAK\ak110.ogg",
"soundAK\ak111.ogg",
"soundAK\ak112.ogg",
"soundAK\ak113.ogg",
"soundAK\ak114.ogg",
"soundAK\ak115.ogg",
"soundAK\ak116.ogg",
"soundAK\ak117.ogg",
"soundAK\ak118.ogg",
"soundAK\ak119.ogg"



];

playSound3D [getMissionPath _s, _unit, false, getPosASL _unit, 4, 1, 0];

};

